import type { SecretPattern } from "./engine.js";

export const SECRET_PATTERNS: SecretPattern[] = [
  {
    id: "sourcegraph-access-token-v3",
    category: "sourcegraph",
    title: "Sourcegraph Access Token (v3)",
    pattern: String.raw`(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40})`,
    keywords: ["sgp_"],
  },
  {
    id: "sourcegraph-access-token-v2",
    category: "sourcegraph",
    title: "Sourcegraph Access Token (v2, deprecated)",
    pattern: String.raw`(sgp_[a-fA-F0-9]{40})`,
    keywords: ["sgp_"],
  },
  {
    id: "sourcegraph-dotcom-user-gateway",
    category: "sourcegraph",
    title: "Sourcegraph Dotcom User Gateway Access Token",
    pattern: String.raw`(sgd_[a-fA-F0-9]{64})`,
    keywords: ["sgd_"],
  },
  {
    id: "sourcegraph-license-key",
    category: "sourcegraph",
    title: "Sourcegraph License Key Token",
    pattern: String.raw`(slk_[a-fA-F0-9]{64})`,
    keywords: ["slk_"],
  },
  {
    id: "sourcegraph-enterprise-subscription",
    category: "sourcegraph",
    title: "Sourcegraph Enterprise subscription Token",
    pattern: String.raw`(sgs_[a-fA-F0-9]{64})`,
    keywords: ["sgs_"],
  },
  {
    id: "sourcegraph-amp",
    category: "sourcegraph",
    title: "Sourcegraph Amp Access Token",
    pattern: String.raw`(sgamp_user_[A-Z0-9]{26}_[a-f0-9]{64})`,
    keywords: ["sgamp_user_"],
  },
  {
    id: "sourcegraph-amp-auth-bypass",
    category: "sourcegraph",
    title: "Sourcegraph Amp Auth Bypass Token",
    pattern: String.raw`(sgamp_user_auth-bypass_[a-zA-Z0-9_-]+)`,
    keywords: ["sgamp_user_auth-bypass_"],
  },
  {
    id: "sourcegraph-workspace-token",
    category: "sourcegraph",
    title: "Sourcegraph Workspace Access Token",
    pattern: String.raw`(sgp_ws[a-fA-F0-9]{32}_[a-fA-F0-9]{40})`,
    keywords: ["sgp_ws"],
  },
  {
    id: "github-pat",
    category: "github",
    title: "GitHub Personal Access Token",
    pattern: String.raw`(ghp_[0-9a-zA-Z]{36})`,
    keywords: ["ghp_"],
  },
  {
    id: "github-oauth",
    category: "github",
    title: "GitHub OAuth Access Token",
    pattern: String.raw`(gho_[0-9a-zA-Z]{36})`,
    keywords: ["gho_"],
  },
  {
    id: "github-app-token",
    category: "github",
    title: "GitHub App Token",
    pattern: String.raw`((ghu|ghs)_[0-9a-zA-Z]{36})`,
    keywords: ["ghu_", "ghs_"],
  },
  {
    id: "github-refresh-token",
    category: "github",
    title: "GitHub Refresh Token",
    pattern: String.raw`(ghr_[0-9a-zA-Z]{76})`,
    keywords: ["ghr_"],
  },
  {
    id: "github-fine-grained-pat",
    category: "github",
    title: "GitHub Fine-grained personal access tokens",
    pattern: String.raw`(github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59})`,
    keywords: ["github_pat_"],
  },
  {
    id: "gitlab-pat",
    category: "gitlab",
    title: "GitLab Personal Access Token",
    pattern: String.raw`(glpat-[0-9a-zA-Z_-]{20})`,
    keywords: ["glpat-"],
  },
  {
    id: "bitbucket-pat",
    category: "bitbucket",
    title: "Bitbucket Personal Access Token",
    pattern: String.raw`(bbpat-[A-Za-z0-9]{20,200})`,
    keywords: ["bbpat-"],
  },
  {
    id: "bitbucket-repo-access-token",
    category: "bitbucket",
    title: "Bitbucket Repository Access Token",
    pattern: String.raw`(bbrat-[A-Za-z0-9]{20,200})`,
    keywords: ["bbrat-"],
  },
  {
    id: "bitbucket-dc-http-token",
    category: "bitbucket",
    title: "Bitbucket DC/Server HTTP Access Token",
    pattern: String.raw`(?:[a-z0-9_ .,-]{0,25}bitbucket[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([A-Za-z0-9+/]{40,80}={0,2})['"]`,
    keywords: ["bitbucket"],
  },
  {
    id: "aws-access-key-id",
    category: "aws",
    title: "AWS Access Key ID",
    pattern: String.raw`((A3T[A-Z0-9]|AKIA|ASIA)[A-Z0-9]{16})`,
    keywords: ["A3T", "AKIA", "ASIA"],
  },
  {
    id: "hugging-face-access-token",
    category: "huggingface",
    title: "Hugging Face Access Token",
    pattern: String.raw`(hf_[A-Za-z0-9]{34,40})`,
    keywords: ["hf_"],
  },
  {
    id: "private-key",
    category: "asymmetric-private-key",
    title: "Asymmetric Private Key",
    pattern: String.raw`-----\s*?BEGIN[ A-Z0-9_-]*?PRIVATE KEY(?: BLOCK)?\s*?-----\s*([A-Za-z0-9=+/\s]+)\s*-----\s*?END[ A-Z0-9_-]*? PRIVATE KEY(?: BLOCK)?\s*?-----`,
    keywords: ["-----"],
    caseInsensitive: true,
  },
  {
    id: "shopify-token",
    category: "shopify",
    title: "Shopify token",
    pattern: String.raw`(shp(ss|at|ca|pa)_[a-fA-F0-9]{32})`,
    keywords: ["shpss_", "shpat_", "shpca_", "shppa_"],
  },
  {
    id: "slack-access-token",
    category: "slack",
    title: "Slack token",
    pattern: String.raw`((xox[baoprs]-|xapp-|xwfp-)([0-9a-zA-Z-]{10,100}))`,
    keywords: ["xoxb-", "xoxa-", "xoxp-", "xoxr-", "xoxs-", "xoxo-", "xapp-", "xwfp-"],
  },
  {
    id: "slack-config-refresh-token",
    category: "slack",
    title: "Slack config refresh token",
    pattern: String.raw`(xoxe-\d-[a-zA-Z0-9]{146})`,
    caseInsensitive: true,
    keywords: ["xoxe-"],
  },
  {
    id: "slack-config-access-token",
    category: "slack",
    title: "Slack config access token",
    pattern: String.raw`(xoxe.xox[bp]-\d-[A-Z0-9]{163,166})`,
    caseInsensitive: true,
    keywords: ["xoxe.xoxb-", "xoxe.xoxp-"],
  },
  {
    id: "slack-web-hook",
    category: "slack",
    title: "Slack Webhook",
    pattern: String.raw`(https:\/\/hooks\.slack\.com\/(services|triggers|workflows)\/[A-Za-z0-9+\/]{43,56})`,
    caseInsensitive: true,
    keywords: ["hooks.slack.com"],
  },
  {
    id: "stripe-secret-token",
    category: "stripe",
    title: "Stripe Secret Key",
    pattern: String.raw`(sk_(test|live)_[0-9a-z]{10,99})`,
    keywords: ["sk_test_", "sk_live_"],
    caseInsensitive: true,
  },
  {
    id: "supabase-service-key",
    category: "supabase",
    title: "Supabase Service Key",
    pattern: String.raw`(sbp_[a-fA-F0-9]{40})`,
    keywords: ["sbp_"],
  },
  {
    id: "pypi-upload-token",
    category: "pypi",
    title: "PyPI upload token",
    pattern: String.raw`(pypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{50,1000})`,
    keywords: ["pypi-AgEIcHlwaS5vcmc"],
  },
  {
    id: "gcp-service-account",
    category: "google",
    title: "Google (GCP) Service-account",
    pattern: String.raw`("type": "service_account")`,
    keywords: ['"type": "service_account"'],
  },
  {
    id: "cloudflare-api-token",
    category: "unknown",
    title: "Cloudflare API Token",
    pattern: String.raw`\b(cfut_[A-Za-z0-9]{48})\b`,
    keywords: ["cfut_"],
  },
  {
    id: "e2b-api-key",
    category: "unknown",
    title: "E2B API Key",
    pattern: String.raw`\b(e2b_[a-f0-9]{40})\b`,
    keywords: ["e2b_"],
  },
  {
    id: "google-api-key",
    category: "google",
    title: "Google API Key",
    pattern: String.raw`\b(AIza[0-9A-Za-z_-]{35,40})\b`,
    keywords: ["AIza"],
  },
  {
    id: "heroku-api-key",
    category: "heroku",
    title: "Heroku API Key",
    pattern: String.raw`(?:heroku[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"](\d[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})['"]`,
    keywords: ["heroku"],
    caseInsensitive: true,
  },
  {
    id: "twilio-api-key",
    category: "twilio",
    title: "Twilio API Key",
    pattern: String.raw`(SK[0-9a-fA-F]{32})`,
    keywords: ["SK"],
  },
  {
    id: "age-secret-key",
    category: "age",
    title: "Age secret key",
    pattern: String.raw`(AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58})`,
    keywords: ["AGE-SECRET-KEY-1"],
  },
  {
    id: "jwt-token",
    category: "jwt",
    title: "JWT token",
    pattern: String.raw`(ey[a-zA-Z0-9]{17,}\.ey[a-zA-Z0-9/\\_-]{17,}\.(?:[a-zA-Z0-9/\\_-]{10,}={0,2})?)`,
    keywords: [".eyJ"],
  },
  {
    id: "npm-access-token",
    category: "npm",
    title: "npm access token",
    pattern: String.raw`(npm_[a-z0-9]{36})`,
    keywords: ["npm_"],
    caseInsensitive: true,
  },
  {
    id: "sendgrid-api-token",
    category: "sendgrid",
    title: "SendGrid API token",
    pattern: String.raw`(SG\.[a-z0-9_.-]{66})`,
    keywords: ["SG."],
    caseInsensitive: true,
  },
  {
    id: "aws-secret-access-key",
    category: "aws",
    title: "AWS Secret Access Key",
    pattern: String.raw`(aws[_-]secret[_-]access[_-]key[_-][A-Za-z0-9/+=]{40})`,
    keywords: ["key"],
    caseInsensitive: true,
  },
  {
    id: "dockerconfig-secret",
    category: "docker",
    title: "Dockerconfig secret exposed",
    pattern: String.raw`((\.dockerconfigjson|dockercfg):\s*\|*\s*((ey|ew)+[A-Za-z0-9/+=]+))`,
    keywords: ["dockerc"],
    caseInsensitive: true,
  },
  {
    id: "linear-api-token",
    category: "linear",
    title: "Linear API token",
    pattern: String.raw`(lin_api_[a-z0-9]{40})`,
    keywords: ["lin_api_"],
    caseInsensitive: true,
  },
  {
    id: "sendinblue-api-token",
    category: "sendinblue",
    title: "Sendinblue API token",
    pattern: String.raw`(xkeysib-[a-f0-9]{64}-[a-z0-9]{16})`,
    keywords: ["xkeysib-"],
    caseInsensitive: true,
  },
  {
    id: "planetscale-api-token",
    category: "planetscale",
    title: "PlanetScale API token",
    pattern: String.raw`(pscale_tkn_[a-z0-9_.-]{43})`,
    keywords: ["pscale_tkn_"],
    caseInsensitive: true,
  },
  {
    id: "doppler-api-token",
    category: "doppler",
    title: "Doppler API token",
    pattern: String.raw`(dp\.pt\.[a-z0-9]{43})`,
    keywords: ["dp.pt."],
    caseInsensitive: true,
  },
  {
    id: "discord-api-token",
    category: "discord",
    title: "Discord API key",
    pattern: String.raw`(?:discord[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{64})['"]`,
    keywords: ["discord"],
    caseInsensitive: true,
  },
  {
    id: "pulumi-api-token",
    category: "pulumi",
    title: "Pulumi API token",
    pattern: String.raw`(pul-[a-f0-9]{40})`,
    keywords: ["pul-"],
  },
  {
    id: "postman-api-token",
    category: "postman",
    title: "Postman API token",
    pattern: String.raw`(PMAK-[a-f0-9]{24}-[a-f0-9]{34})`,
    keywords: ["PMAK-"],
    caseInsensitive: true,
  },
  {
    id: "facebook-token",
    category: "facebook",
    title: "Facebook token",
    pattern: String.raw`(?:facebook[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]`,
    keywords: ["facebook"],
    caseInsensitive: true,
  },
  {
    id: "twitter-token",
    category: "twitter",
    title: "Twitter token",
    pattern: String.raw`(?:twitter[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{35,44})['"]`,
    keywords: ["twitter"],
    caseInsensitive: true,
  },
  {
    id: "adobe-client-id",
    category: "adobe",
    title: "Adobe Client ID (Oauth Web)",
    pattern: String.raw`(?:adobe[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]`,
    keywords: ["adobe"],
    caseInsensitive: true,
  },
  {
    id: "adobe-client-secret",
    category: "adobe",
    title: "Adobe Client Secret",
    pattern: String.raw`(p8e-[a-z0-9]{32})`,
    keywords: ["p8e-"],
    caseInsensitive: true,
  },
  {
    id: "alibaba-access-key-id",
    category: "alibaba",
    title: "Alibaba AccessKey ID",
    pattern: String.raw`((LTAI)[a-z0-9]{20})`,
    keywords: ["LTAI"],
    caseInsensitive: true,
  },
  {
    id: "alibaba-secret-key",
    category: "alibaba",
    title: "Alibaba Secret Key",
    pattern: String.raw`(?:alibaba[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{30})['"]`,
    keywords: ["alibaba"],
    caseInsensitive: true,
  },
  {
    id: "asana-client-id",
    category: "asana",
    title: "Asana Client ID",
    pattern: String.raw`(?:asana[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([0-9]{16})['"]`,
    keywords: ["asana"],
    caseInsensitive: true,
  },
  {
    id: "asana-client-secret",
    category: "asana",
    title: "Asana Client Secret",
    pattern: String.raw`(?:asana[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{32})['"]`,
    keywords: ["asana"],
    caseInsensitive: true,
  },
  {
    id: "atlassian-api-token",
    category: "atlassian",
    title: "Atlassian API token",
    pattern: String.raw`(?:atlassian[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{24})['"]`,
    keywords: ["atlassian"],
    caseInsensitive: true,
  },
  {
    id: "beamer-api-token",
    category: "beamer",
    title: "Beamer API token",
    pattern: String.raw`(?:beamer[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"](b_[a-z0-9=_-]{44})['"]`,
    keywords: ["beamer"],
    caseInsensitive: true,
  },
  {
    id: "buildkite-agent-token",
    category: "buildkite",
    title: "Buildkite API Token V2",
    pattern: String.raw`(bkua_[a-fA-F0-9]{40})`,
    keywords: ["bkua_"],
  },
  {
    id: "clojars-api-token",
    category: "clojars",
    title: "Clojars API token",
    pattern: String.raw`(CLOJARS_[a-z0-9]{60})`,
    keywords: ["CLOJARS_"],
    caseInsensitive: true,
  },
  {
    id: "contentful-delivery-api-token",
    category: "contentful-delivery",
    title: "Contentful delivery API token",
    pattern: String.raw`(?:contentful[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_-]{43})['"]`,
    keywords: ["contentful"],
    caseInsensitive: true,
  },
  {
    id: "databricks-api-token",
    category: "databricks",
    title: "Databricks API token",
    pattern: String.raw`(dapi[a-h0-9]{32})`,
    keywords: ["dapi"],
  },
  {
    id: "discord-client-id",
    category: "discord",
    title: "Discord client ID",
    pattern: String.raw`(?:discord[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([0-9]{18})['"]`,
    keywords: ["discord"],
    caseInsensitive: true,
  },
  {
    id: "discord-client-secret",
    category: "discord",
    title: "Discord client secret",
    pattern: String.raw`(?:discord[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_-]{32})['"]`,
    keywords: ["discord"],
    caseInsensitive: true,
  },
  {
    id: "dropbox-api-secret",
    category: "dropbox",
    title: "Dropbox API secret/key",
    pattern: String.raw`(?:dropbox[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{15})['"]`,
    keywords: ["dropbox"],
    caseInsensitive: true,
  },
  {
    id: "dropbox-short-lived-api-token",
    category: "dropbox",
    title: "Dropbox short lived API token",
    pattern: String.raw`(?:dropbox[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"](sl\.[a-z0-9=_-]{135})['"]`,
    keywords: ["dropbox"],
    caseInsensitive: true,
  },
  {
    id: "dropbox-long-lived-api-token",
    category: "dropbox",
    title: "Dropbox long lived API token",
    pattern: String.raw`(?:dropbox[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9_=-]{43})['"]`,
    keywords: ["dropbox"],
    caseInsensitive: true,
  },
  {
    id: "duffel-api-token",
    category: "duffel",
    title: "Duffel API token",
    pattern: String.raw`(duffel_(test|live)_[a-z0-9_-]{43})`,
    keywords: ["duffel_test_", "duffel_live_"],
    caseInsensitive: true,
  },
  {
    id: "dynatrace-api-token",
    category: "dynatrace",
    title: "Dynatrace API token",
    pattern: String.raw`(dt0c01\.[a-z0-9]{24}\.[a-z0-9]{64})`,
    keywords: ["dt0c01."],
    caseInsensitive: true,
  },
  {
    id: "easypost-api-token",
    category: "easypost",
    title: "EasyPost API token",
    pattern: String.raw`(EZ[AT]K[a-z0-9]{54})`,
    keywords: ["EZAK", "EZAT"],
    caseInsensitive: true,
  },
  {
    id: "fastly-api-token",
    category: "fastly",
    title: "Fastly API token",
    pattern: String.raw`(?:fastly[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_-]{32})['"]`,
    keywords: ["fastly"],
    caseInsensitive: true,
  },
  {
    id: "finicity-client-secret",
    category: "finicity",
    title: "Finicity client secret",
    pattern: String.raw`(?:finicity[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{20})['"]`,
    keywords: ["finicity"],
    caseInsensitive: true,
  },
  {
    id: "finicity-api-token",
    category: "finicity",
    title: "Finicity API token",
    pattern: String.raw`(?:finicity[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]`,
    keywords: ["finicity"],
    caseInsensitive: true,
  },
  {
    id: "flutterwave-public-key",
    category: "flutterwave",
    title: "Flutterwave public/secret key",
    pattern: String.raw`(FLW(PUB|SEC)K_TEST-[a-h0-9]{32}-X)`,
    keywords: ["FLWSECK_TEST-", "FLWPUBK_TEST-"],
    caseInsensitive: true,
  },
  {
    id: "flutterwave-enc-key",
    category: "flutterwave",
    title: "Flutterwave encrypted key",
    pattern: String.raw`(FLWSECK_TEST[a-h0-9]{12})`,
    keywords: ["FLWSECK_TEST"],
  },
  {
    id: "frameio-api-token",
    category: "frameio",
    title: "Frame.io API token",
    pattern: String.raw`(fio-u-[a-z0-9_=-]{64})`,
    keywords: ["fio-u-"],
    caseInsensitive: true,
  },
  {
    id: "gocardless-api-token",
    category: "gocardless",
    title: "GoCardless API token",
    pattern: String.raw`(live_[a-z0-9_=-]{40})`,
    keywords: ["live_"],
    caseInsensitive: true,
  },
  {
    id: "grafana-api-token",
    category: "grafana",
    title: "Grafana API token",
    pattern: String.raw`(eyJrIjoi[a-z0-9_=-]{72,92})`,
    keywords: ["eyJrIjoi"],
    caseInsensitive: true,
  },
  {
    id: "hashicorp-tf-api-token",
    category: "hashicorp",
    title: "HashiCorp Terraform user/org API token",
    pattern: String.raw`([a-z0-9]{14}\.atlasv1\.[a-z0-9_=-]{60,70})`,
    keywords: ["atlasv1."],
    caseInsensitive: true,
  },
  {
    id: "hubspot-api-token",
    category: "hubspot",
    title: "HubSpot API token",
    pattern: String.raw`(?:hubspot[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]`,
    keywords: ["hubspot"],
    caseInsensitive: true,
  },
  {
    id: "intercom-api-token",
    category: "intercom",
    title: "Intercom API token",
    pattern: String.raw`(?:intercom[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9=_]{60})['"]`,
    keywords: ["intercom"],
    caseInsensitive: true,
  },
  {
    id: "intercom-client-secret",
    category: "intercom",
    title: "Intercom client secret/ID",
    pattern: String.raw`(?:intercom[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]`,
    keywords: ["intercom"],
    caseInsensitive: true,
  },
  {
    id: "ionic-api-token",
    category: "ionic",
    title: "Ionic API token",
    pattern: String.raw`(?:ionic[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"](ion_[a-z0-9]{42})['"]`,
    keywords: ["ionic"],
    caseInsensitive: true,
  },
  {
    id: "linear-client-secret",
    category: "linear",
    title: "Linear client secret/ID",
    pattern: String.raw`(?:linear[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32})['"]`,
    keywords: ["linear"],
    caseInsensitive: true,
  },
  {
    id: "lob-api-key",
    category: "lob",
    title: "Lob API Key",
    pattern: String.raw`(?:lob[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]((live|test)_[a-f0-9]{35})['"]`,
    keywords: ["lob"],
    caseInsensitive: true,
  },
  {
    id: "mailchimp-api-key",
    category: "mailchimp",
    title: "Mailchimp API key",
    pattern: String.raw`(?:mailchimp[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-f0-9]{32}-us20)['"]`,
    keywords: ["mailchimp"],
    caseInsensitive: true,
  },
  {
    id: "mailgun-token",
    category: "mailgun",
    title: "Mailgun private API token",
    pattern: String.raw`(?:mailgun[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]((pub)?key-[a-f0-9]{32})['"]`,
    keywords: ["mailgun"],
    caseInsensitive: true,
  },
  {
    id: "mailgun-signing-key",
    category: "mailgun",
    title: "Mailgun webhook signing key",
    pattern: String.raw`(?:mailgun[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})['"]`,
    keywords: ["mailgun"],
    caseInsensitive: true,
  },
  {
    id: "mapbox-api-token",
    category: "mapbox",
    title: "Mapbox API token",
    pattern: String.raw`(pk\.[a-z0-9]{60}\.[a-z0-9]{22})`,
    keywords: ["pk."],
    caseInsensitive: true,
  },
  {
    id: "messagebird-api-token",
    category: "messagebird",
    title: "MessageBird API token",
    pattern: String.raw`(?:messagebird[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{25})['"]`,
    keywords: ["messagebird"],
    caseInsensitive: true,
  },
  {
    id: "messagebird-client-id",
    category: "messagebird",
    title: "MessageBird API client ID",
    pattern: String.raw`(?:messagebird[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['"]`,
    keywords: ["messagebird"],
    caseInsensitive: true,
  },
  {
    id: "new-relic-user-api-key",
    category: "newrelic",
    title: "New Relic user API Key",
    pattern: String.raw`(NRAK-[A-Z0-9]{27})`,
    keywords: ["NRAK-"],
  },
  {
    id: "new-relic-user-api-id",
    category: "newrelic",
    title: "New Relic user API ID",
    pattern: String.raw`(?:newrelic[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([A-Z0-9]{64})['"]`,
    keywords: ["newrelic"],
    caseInsensitive: true,
  },
  {
    id: "new-relic-browser-api-token",
    category: "newrelic",
    title: "New Relic ingest browser API token",
    pattern: String.raw`(NRJS-[a-f0-9]{19})`,
    keywords: ["NRJS-"],
  },
  {
    id: "planetscale-password",
    category: "planetscale",
    title: "PlanetScale password",
    pattern: String.raw`(pscale_pw_[a-z0-9_.-]{43})`,
    keywords: ["pscale_pw_"],
    caseInsensitive: true,
  },
  {
    id: "private-packagist-token",
    category: "private-packagist",
    title: "Private Packagist token",
    pattern: String.raw`(packagist_[ou][ru]t_[a-f0-9]{68})`,
    keywords: ["packagist_uut_", "packagist_ort_", "packagist_out_"],
    caseInsensitive: true,
  },
  {
    id: "rubygems-api-token",
    category: "rubygems",
    title: "Rubygem API token",
    pattern: String.raw`(rubygems_[a-f0-9]{48})`,
    keywords: ["rubygems_"],
  },
  {
    id: "shippo-api-token",
    category: "shippo",
    title: "Shippo API token",
    pattern: String.raw`(shippo_(live|test)_[a-f0-9]{40})`,
    keywords: ["shippo_live_", "shippo_test_"],
  },
  {
    id: "linkedin-client-secret",
    category: "linkedin",
    title: "LinkedIn Client secret",
    pattern: String.raw`(?:linkedin[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z]{16})['"]`,
    keywords: ["linkedin"],
    caseInsensitive: true,
  },
  {
    id: "linkedin-client-id",
    category: "linkedin",
    title: "LinkedIn Client ID",
    pattern: String.raw`(?:linkedin[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{14})['"]`,
    keywords: ["linkedin"],
    caseInsensitive: true,
  },
  {
    id: "twitch-api-token",
    category: "twitch",
    title: "Twitch API token",
    pattern: String.raw`(?:twitch[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}['"]([a-z0-9]{30})['"]`,
    keywords: ["twitch"],
    caseInsensitive: true,
  },
  {
    id: "typeform-api-token",
    category: "typeform",
    title: "Typeform API token",
    pattern: String.raw`(?:typeform[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:).{0,5}(tfp_[a-z0-9_.=-]{59})`,
    keywords: ["typeform"],
    caseInsensitive: true,
  },
  {
    id: "todoist-api-token",
    category: "todoist",
    title: "Todoist API token",
    pattern: String.raw`(?:todoist[a-z0-9_ .,-]{0,25})(?:=|>|:=|\|\|:|<=|=>|:)[\s'"]{0,3}([0-9a-f]{40})`,
    keywords: ["todoist"],
    caseInsensitive: true,
  },
  {
    id: "openai-api-key",
    category: "openai",
    title: "OpenAI API Key",
    pattern: String.raw`(sk-[a-zA-Z0-9]{50})`,
    caseInsensitive: false,
    keywords: ["sk-"],
  },
  {
    id: "openai-api-key-project",
    category: "openai",
    title: "OpenAI Project-scoped API Key",
    pattern: String.raw`(sk-proj-[A-Za-z0-9]{24}-[A-Za-z0-9]{40,128})`,
    caseInsensitive: true,
    keywords: ["sk-proj-"],
  },
  {
    id: "openai-api-key-env",
    category: "openai",
    title: "OpenAI Environment-scoped API Key",
    pattern: String.raw`(sk-(?:live|test)-[A-Za-z0-9]{24}-[A-Za-z0-9]{40,128})`,
    caseInsensitive: true,
    keywords: ["sk-live-", "sk-test-"],
  },
  {
    id: "anthropic-api-key",
    category: "anthropic",
    title: "Anthropic API Key",
    pattern: String.raw`(sk-ant-([a-zA-Z0-9]{1,10}-)?[a-zA-Z0-9_-]{32,128})`,
    caseInsensitive: false,
    keywords: ["sk-ant-"],
  },
  {
    id: "canva-token",
    category: "canva",
    title: "Canva Token",
    pattern: String.raw`\b(cnv[a-z0-9]{2}[A-Za-z0-9_=-]+[a-f0-9]{8})\b`,
    caseInsensitive: false,
    keywords: ["cnv"],
  },
  {
    id: "api-key",
    category: "unknown",
    title: "Unknown API Key",
    // End boundary is "not a value char" so keys glued to Chinese/CJK punctuation
    // still match (e.g. "api_key=xxx我问的").
    pattern: String.raw`(?:[a-z0-9_ .,-]{0,25}api[-_](?:key|token)(?!length|count|max|min|maxlength|_length|_count|_min|_maxlength)[a-z0-9_ .,-]{0,25})\s*(?:=|>|:=|\|\|:|<=|=>|:)\s*['"]?((?!.*(?:api|key|secret|foo|example|dummy|password|12345|abcde|placeholder|fake|token))[a-z0-9+/_-]{6,128})['"]?(?![a-z0-9+/_-])`,
    keywords: ["api-key", "api_key", "api-token", "api_token"],
    caseInsensitive: true,
  },
  {
    id: "webhook-secret",
    category: "unknown",
    title: "Unknown Webhook Secret",
    pattern: String.raw`(?:[a-z0-9_ .,-]{0,25}webhook[-_]secret(?!length|count|max|min|maxlength|_length|_count|_min|_maxlength)[a-z0-9_ .,-]{0,25})\s*(?:=|>|:=|\|\|:|<=|=>|:)\s*['"]?((?!.*(?:api|key|secret|foo|example|dummy|password|12345|abcde|placeholder|fake|token|webhook))[a-z0-9+/=_-]{6,128})['"]?(?![a-z0-9+/=_-])`,
    keywords: ["webhook-secret", "webhook_secret"],
    caseInsensitive: true,
  },
  {
    id: "secret-value",
    category: "unknown",
    title: "Unknown API Key",
    pattern: String.raw`(?:[a-z0-9_ .,-]{0,25}[-_](?:secret)(?!length|count|max|min|maxlength|_length|_count|_min|_maxlength)[a-z0-9_ .,-]{0,25})\s*(?:=|>|:=|\|\|:|<=|=>|:)\s*['"]?((?!.*(?:api|key|secret|foo|example|dummy|password|12345|abcde|placeholder|fake|token))[a-z0-9+/_-]{6,128})['"]?(?![a-z0-9+/_-])`,
    keywords: ["secret"],
    caseInsensitive: true,
  },
  {
    id: "password",
    category: "unknown",
    title: "Unknown Password",
    pattern: String.raw`(?:[a-z0-9_ .,-]{0,25}password(?!length|count|max|min|maxlength|_length|_count|_min|_maxlength)[a-z0-9_ .,-]{0,25})\s*(?:=|>|:=|\|\|:|<=|=>|:)\s*['"]?((?!.*(?:api|key|secret|foo|example|dummy|string|password|12345|abcde|placeholder|fake|token|password|pass|pwd))[a-z0-9+/=_-]{6,128})['"]?(?![a-z0-9+/=_-])`,
    keywords: ["password"],
    caseInsensitive: true,
  },
  {
    id: "sk-secret",
    category: "unknown",
    title: "Unknown SK Secret",
    // Word-ish boundaries (non-alphanumeric) instead of whitespace-only so
    // keys glued to Chinese text or punctuation still match:
    //   "sk-xxx我输入了什么？"  "key=sk-xxx"  "sk-xxx，"
    // Still avoids matching identifiers like "mysk-..." or trailing alnum.
    pattern: String.raw`(?<![a-z0-9])(sk(?:[-_][a-z0-9]{1,10})?[-_][a-z0-9]{10,99})(?![a-z0-9])`,
    caseInsensitive: true,
    keywords: ["sk-", "sk_"],
  },
];
